### PR TITLE
Fix/edit list returns

### PR DESCRIPTION
**Pull request by vshia**
@davidlibland Can you see if this captures all of your changes?  I removed Bisoye's slate-react-native changes from the master since it isn't ready and it was causing problems with the local installs.

I cherry-picked all of your changes except for https://github.com/humandx/slate/pull/4/commits/e0a33120bc51d87577e7c88fbc690837fe02f3bc
I wasn't able to cherry-pick that commit for some reason.

### CODE REVIEW

**Comment by davidlibland** [comment]
@vshia Thanks! Yes, this contains all the changes.

**Comment by davidlibland** [comment]
@vshia Do you know how these changes affect android?

**Comment by nathanfu88** [comment]
Slate currently has issues with later versions of Android due to Google's choice to not send keyCodes with virtual keyboard button presses. We're currently looking into how to implement a workaround for this, so I would suggest we worry about Android in a different branch/issue.

**Review by nathanfu88 — COMMENTED** [review]
I have not been able to test these changes on an iOS device yet, but the changes here look appropriate.

**Comment by ben-harack** [comment]
I'm guessing that we don't need this still. Closing.

**Pull request closed without merging**
